=== Shmuma/tablix-operators/tablix2-0.3.5/examples/tablix2r1.dtd
<!-- ======================================================================

     Tablix Timetabling Model XML DTD, version 0.2.0R1
     File tablix2r1.dtd

     Copyright (C) 2002-2006 Tomaz Solc

     This program is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation; either version 2 of the License, or
     (at your option) any later version.

     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with this program; if not, write to the Free Software
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

     $Id: tablix2r1.dtd,v 1.1 2006-03-27 16:04:20 avian Exp $
     
     ====================================================================== 
     
     This is an XML document type definition (DTD) file for files describing
     timetabling problems according to the Tablix timetabling model version
     0.2.0.
     
     Please use the following DOCTYPE declaration to identify this file:
     
	<!DOCTYPE ttm PUBLIC "-//Tablix//DTD TTM 0.2.0//EN" 
			"http://www.tablix.org/releases/dtd/tablix2r1.dtd"> 
	
     ====================================================================== -->

<!ELEMENT ttm (info?,modules,resources,events)>
	<!ATTLIST ttm version CDATA #REQUIRED
	              fitness CDATA #IMPLIED>
        <!ELEMENT info (title?,address?,author?)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT address (#PCDATA)>
                <!ELEMENT author (#PCDATA)>
        <!ELEMENT modules (module+)>
                <!ELEMENT module (option*)>
		<!ATTLIST module name CDATA #REQUIRED
				 weight CDATA #REQUIRED
				 mandatory (yes|no) #REQUIRED>
			<!ELEMENT option (#PCDATA)>
			<!ATTLIST option name CDATA #REQUIRED>
        <!ELEMENT resources (constant?,variable?)>
                <!ELEMENT constant (resourcetype+)>
		<!ELEMENT variable (resourcetype+)>
			<!ELEMENT resourcetype ((resource|linear|matrix)+)>
                	<!ATTLIST resourcetype type CDATA #REQUIRED
			                       typeid CDATA #IMPLIED>
				<!ELEMENT resource (restriction*)>
				<!ATTLIST resource name CDATA #REQUIRED
				                   type CDATA #IMPLIED
						   resid CDATA #IMPLIED>
				<!ELEMENT linear (restriction*)>
				<!ATTLIST linear name CDATA #REQUIRED
				                 from CDATA #REQUIRED
						 to CDATA #REQUIRED
						 resid-from CDATA #IMPLIED
						 resid-to CDATA #IMPLIED>
				<!ELEMENT matrix (restriction*)>
				<!ATTLIST matrix width CDATA #REQUIRED
				                 height CDATA #REQUIRED
						 resid-from CDATA #IMPLIED
						 resid-to CDATA #IMPLIED>
        <!ELEMENT events (event+)>
		<!ELEMENT event (resource|restriction)*>
		<!ATTLIST event name CDATA #REQUIRED
		                repeats CDATA #REQUIRED
				tupleid CDATA #IMPLIED>

        <!ELEMENT restriction (#PCDATA)>
        <!ATTLIST restriction type CDATA #REQUIRED>

=== Shmuma/tablix-operators/result1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ttm PUBLIC "-//Tablix//DTD TTM 0.2.0//EN" "http://www.tablix.org/releases/dtd/tablix2r1.dtd">
<ttm version="0.2.0" fitness="800">
  <info>
    <title>User's preferences module test</title>
    <address>www.yandex.ru</address>
    <author>Max Lapan</author>
  </info>
  <modules>
    <module name="available" weight="200" mandatory="yes"/>
    <module name="timeplace" weight="500" mandatory="yes"/>
    <module name="sametimelight" weight="500" mandatory="yes"/>
    <module name="room_available" weight="500" mandatory="yes">
      <option name="debug">0</option>
    </module>
    <module name="preference" weight="50" mandatory="no"/>
    <module name="time_descriptions" weight="0" mandatory="no">
      <option name="output">time_descr.txt</option>
    </module>
  </modules>

  <resources>
    <constant>
      <resourcetype type="operator" typeid="0">
        <resource name="airdog" resid="0"/>
        <resource name="alex27j" resid="1"/>
        <resource name="astronom" resid="2"/>
        <resource name="shpin" resid="3">
          <restriction type="pref-room">!2 ETO</restriction>
          <restriction type="pref-room">1 Golem</restriction>
        </resource>
        <resource name="teran" resid="4">
          <restriction type="pref-room">2 ETO</restriction>
          <restriction type="pref-room">2 Vavilova</restriction>
          <restriction type="pref-time-day">!2 0</restriction>
          <restriction type="pref-time-time">!2 0</restriction>
          <restriction type="pref-time-cell">!2 1 2</restriction>
        </resource>
        <resource name="shmuma" resid="5">
          <restriction type="pref-room">1 Vavilova</restriction>
          <restriction type="pref-room">!1 ETO</restriction>
        </resource>
      </resourcetype>
    </constant>

    <variable>
      <resourcetype type="time" typeid="1">
        <matrix width="7" height="3" resid-from="0" resid-to="20"/>
      </resourcetype>

      <resourcetype type="room" typeid="2">
        <resource name="Vavilova" resid="0">
          <restriction type="time-descriptions">23:00,07:00,15:00</restriction>
          <restriction type="room-not-available-time">0</restriction>
          <restriction type="room-not-available-day">5</restriction>
          <restriction type="room-not-available-day">6</restriction>
        </resource>
        <resource name="ETO" resid="1">
          <restriction type="time-descriptions">23:00,07:00,15:00</restriction>
          <restriction type="room-must-be-filled">0</restriction>
          <restriction type="room-must-be-filled">1</restriction>
          <restriction type="room-must-be-filled">2</restriction>
          <restriction type="room-not-available-cell">1 2</restriction>
          <restriction type="room-not-available-day">5</restriction>
        </resource>
        <resource name="Golem" resid="2">
          <restriction type="room-must-be-filled">0</restriction>
          <restriction type="room-must-be-filled">1</restriction>
          <restriction type="time-descriptions">23:00,07:00,15:00</restriction>
        </resource>
      </resourcetype>
    </variable>
  </resources>

  <events>
    <event name="Work" repeats="1" tupleid="0">
        <resource type="operator" name="airdog"/>
    	<resource type="time" name="3 0"/>
			<resource type="room" name="Golem"/>
		</event><event name="Work" repeats="1" tupleid="1">
        <resource type="operator" name="airdog"/>
    	<resource type="time" name="1 0"/>
			<resource type="room" name="Golem"/>
		</event><event name="Work" repeats="1" tupleid="2">
        <resource type="operator" name="airdog"/>
    	<resource type="time" name="6 0"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="3">
        <resource type="operator" name="airdog"/>
    	<resource type="time" name="4 0"/>
			<resource type="room" name="ETO"/>
		</event>
    <event name="Work" repeats="1" tupleid="4">
        <resource type="operator" name="alex27j"/>
    	<resource type="time" name="4 1"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="5">
        <resource type="operator" name="alex27j"/>
    	<resource type="time" name="1 1"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="6">
        <resource type="operator" name="alex27j"/>
    	<resource type="time" name="4 0"/>
			<resource type="room" name="Golem"/>
		</event><event name="Work" repeats="1" tupleid="7">
        <resource type="operator" name="alex27j"/>
    	<resource type="time" name="2 0"/>
			<resource type="room" name="ETO"/>
		</event>
    <event name="Work" repeats="1" tupleid="8">
        <resource type="operator" name="astronom"/>
    	<resource type="time" name="5 0"/>
			<resource type="room" name="Golem"/>
		</event><event name="Work" repeats="1" tupleid="9">
        <resource type="operator" name="astronom"/>
    	<resource type="time" name="1 0"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="10">
        <resource type="operator" name="astronom"/>
    	<resource type="time" name="3 1"/>
			<resource type="room" name="Golem"/>
		</event><event name="Work" repeats="1" tupleid="11">
        <resource type="operator" name="astronom"/>
    	<resource type="time" name="2 1"/>
			<resource type="room" name="ETO"/>
		</event>
    <event name="Work" repeats="1" tupleid="12">
        <resource type="operator" name="shpin"/>
    	<resource type="time" name="0 1"/>
			<resource type="room" name="Golem"/>
		</event><event name="Work" repeats="1" tupleid="13">
        <resource type="operator" name="shpin"/>
    	<resource type="time" name="4 1"/>
			<resource type="room" name="Golem"/>
		</event><event name="Work" repeats="1" tupleid="14">
        <resource type="operator" name="shpin"/>
    	<resource type="time" name="6 0"/>
			<resource type="room" name="Golem"/>
		</event><event name="Work" repeats="1" tupleid="15">
        <resource type="operator" name="shpin"/>
    	<resource type="time" name="0 0"/>
			<resource type="room" name="Golem"/>
		</event>
    <event name="Work" repeats="1" tupleid="16">
        <resource type="operator" name="teran"/>
    	<resource type="time" name="3 2"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="17">
        <resource type="operator" name="teran"/>
    	<resource type="time" name="2 2"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="18">
        <resource type="operator" name="teran"/>
    	<resource type="time" name="6 1"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="19">
        <resource type="operator" name="teran"/>
    	<resource type="time" name="0 2"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="20">
        <resource type="operator" name="teran"/>
    	<resource type="time" name="0 0"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="21">
        <resource type="operator" name="teran"/>
    	<resource type="time" name="0 1"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="22">
        <resource type="operator" name="teran"/>
    	<resource type="time" name="4 2"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="23">
        <resource type="operator" name="teran"/>
    	<resource type="time" name="3 0"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="24">
        <resource type="operator" name="teran"/>
    	<resource type="time" name="3 1"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="25">
        <resource type="operator" name="teran"/>
    	<resource type="time" name="4 1"/>
			<resource type="room" name="Vavilova"/>
		</event>
    <event name="Work" repeats="1" tupleid="26">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="2 1"/>
			<resource type="room" name="Golem"/>
		</event><event name="Work" repeats="1" tupleid="27">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="5 1"/>
			<resource type="room" name="Golem"/>
		</event><event name="Work" repeats="1" tupleid="28">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="4 2"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="29">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="6 2"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="30">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="5 2"/>
			<resource type="room" name="Golem"/>
		</event><event name="Work" repeats="1" tupleid="31">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="2 0"/>
			<resource type="room" name="Golem"/>
		</event><event name="Work" repeats="1" tupleid="32">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="6 1"/>
			<resource type="room" name="Golem"/>
		</event><event name="Work" repeats="1" tupleid="33">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="2 2"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="34">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="1 2"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="35">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="1 1"/>
			<resource type="room" name="Golem"/>
		</event>
  </events>
</ttm>
<!-- End of file -->
<!-- End of file -->

=== Shmuma/tablix-operators/tablix2-0.3.5/ttf/tests/bug-consecutive-fixedtime-1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ttm PUBLIC "-//Tablix//DTD TTM 0.2.0//EN" "http://www.tablix.org/releases/dtd/tablix2r1.dtd">
<!--
BEGIN TTF BLOCK
(define periods 10)

(define (get-day tupleid) (quotient (get-time tupleid) periods))

(define (tuple-loop i j ok)
	(if (< i j)
		(tuple-loop (+ i 1) j 
			(and 
				ok 
				(time i (+ (get-time (- i 1)) 1))
				(= 
					(quotient (get-time i) 10) 
					(quotient (get-time (- i 1)) 10)
				)
			)
		)
		ok
	)
	
)
(test-ttf
	(tuple-loop 2 7 #t)
	(= (get-day 6) 0)
)
END TTF BLOCK
-->
<ttm version="0.2.0">
	<modules>
		<module name="sametime.so" weight="60" mandatory="yes"/> 
		<module name="timeplace.so" weight="60" mandatory="yes"/>
		<module name="consecutive.so" weight="60" mandatory="yes"/>
		<module name="fixedtime.so" weight="60" mandatory="yes"/>
	</modules>

	<resources>
		<constant>
			<resourcetype type="teacher">
				<resource name="a"/>
			</resourcetype>
			<resourcetype type="class">
				<linear name="#" from="1" to="3"/>
			</resourcetype>
		</constant>
		<variable>
			<resourcetype type="room">
				<linear name="#" from="1" to="40"/>
			</resourcetype>
			<resourcetype type="time">
				<matrix width="10" height="10"/>
			</resourcetype>
		</variable>
	</resources>

	<events>
		<!-- 0 -->
		<event name="test" repeats="1">
			<resource type="teacher" name="a"/>
			<resource type="class" name="1"/>
		</event>
		<!-- 1,2,3,4,5 -->
		<event name="test" repeats="5">
			<resource type="teacher" name="a"/>
			<resource type="class" name="2"/>
			<restriction type="consecutive"/>
		</event>
		<!-- 6 -->
		<event name="test" repeats="1">
			<resource type="teacher" name="a"/>
			<resource type="class" name="2"/>
			<restriction type="consecutive"/>
			<restriction type="fixed-day">0</restriction>
		</event>
		<event name="test" repeats="1">
			<resource type="teacher" name="a"/>
			<resource type="class" name="3"/>
		</event>
	</events>
</ttm>

=== Shmuma/tablix-operators/result0.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ttm PUBLIC "-//Tablix//DTD TTM 0.2.0//EN" "http://www.tablix.org/releases/dtd/tablix2r1.dtd">
<ttm version="0.2.0" fitness="0">
  <info>
    <title>Shifts sanity module test</title>
    <address>www.yandex.ru</address>
    <author>Max Lapan</author>
  </info>
  <modules>
    <module name="available" weight="200" mandatory="yes"/>
    <module name="timeplace" weight="500" mandatory="yes"/>
    <module name="sametimelight" weight="500" mandatory="yes"/>
    <module name="shifts" weight="500" mandatory="yes">
      <option name="max-nights-per-week">2</option>
      <option name="max-nights-weight">100</option>
    </module>
  </modules>

  <resources>
    <constant>
      <resourcetype type="operator" typeid="0">
        <resource name="airdog" resid="0"/>
        <resource name="alex27j" resid="1"/>
        <resource name="astronom" resid="2"/>
        <resource name="shpin" resid="3"/>
        <resource name="teran" resid="4"/>
        <resource name="shmuma" resid="5"/>
      </resourcetype>
    </constant>

    <variable>
      <resourcetype type="time" typeid="1">
        <matrix width="7" height="3" resid-from="0" resid-to="20"/>
      </resourcetype>

      <resourcetype type="room" typeid="2">
        <resource name="Vavilova" resid="0">
        </resource>
        <resource name="ETO" resid="1">
        </resource>
      </resourcetype>
    </variable>
  </resources>

  <events>
    <event name="Work" repeats="1" tupleid="0">
        <resource type="operator" name="airdog"/>
    	<resource type="time" name="4 2"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="1">
        <resource type="operator" name="airdog"/>
    	<resource type="time" name="1 2"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="2">
        <resource type="operator" name="airdog"/>
    	<resource type="time" name="2 1"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="3">
        <resource type="operator" name="airdog"/>
    	<resource type="time" name="2 0"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="4">
        <resource type="operator" name="airdog"/>
    	<resource type="time" name="5 0"/>
			<resource type="room" name="ETO"/>
		</event>
    <event name="Work" repeats="1" tupleid="5">
        <resource type="operator" name="alex27j"/>
    	<resource type="time" name="5 1"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="6">
        <resource type="operator" name="alex27j"/>
    	<resource type="time" name="6 0"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="7">
        <resource type="operator" name="alex27j"/>
    	<resource type="time" name="4 1"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="8">
        <resource type="operator" name="alex27j"/>
    	<resource type="time" name="4 2"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="9">
        <resource type="operator" name="alex27j"/>
    	<resource type="time" name="0 0"/>
			<resource type="room" name="Vavilova"/>
		</event>
    <event name="Work" repeats="1" tupleid="10">
        <resource type="operator" name="astronom"/>
    	<resource type="time" name="3 0"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="11">
        <resource type="operator" name="astronom"/>
    	<resource type="time" name="3 2"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="12">
        <resource type="operator" name="astronom"/>
    	<resource type="time" name="2 2"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="13">
        <resource type="operator" name="astronom"/>
    	<resource type="time" name="3 1"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="14">
        <resource type="operator" name="astronom"/>
    	<resource type="time" name="0 0"/>
			<resource type="room" name="ETO"/>
		</event>
    <event name="Work" repeats="1" tupleid="15">
        <resource type="operator" name="shpin"/>
    	<resource type="time" name="0 1"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="16">
        <resource type="operator" name="shpin"/>
    	<resource type="time" name="1 1"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="17">
        <resource type="operator" name="shpin"/>
    	<resource type="time" name="3 2"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="18">
        <resource type="operator" name="shpin"/>
    	<resource type="time" name="4 0"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="19">
        <resource type="operator" name="shpin"/>
    	<resource type="time" name="6 2"/>
			<resource type="room" name="Vavilova"/>
		</event>
    <event name="Work" repeats="1" tupleid="20">
        <resource type="operator" name="teran"/>
    	<resource type="time" name="0 1"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="21">
        <resource type="operator" name="teran"/>
    	<resource type="time" name="4 0"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="22">
        <resource type="operator" name="teran"/>
    	<resource type="time" name="2 0"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="23">
        <resource type="operator" name="teran"/>
    	<resource type="time" name="3 1"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="24">
        <resource type="operator" name="teran"/>
    	<resource type="time" name="2 2"/>
			<resource type="room" name="ETO"/>
		</event>
    <event name="Work" repeats="1" tupleid="25">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="0 2"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="26">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="1 0"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="27">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="5 2"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="28">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="6 0"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="29">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="1 1"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="30">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="5 1"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="31">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="6 1"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="32">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="2 1"/>
			<resource type="room" name="ETO"/>
		</event><event name="Work" repeats="1" tupleid="33">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="4 1"/>
			<resource type="room" name="Vavilova"/>
		</event><event name="Work" repeats="1" tupleid="34">
        <resource type="operator" name="shmuma"/>
    	<resource type="time" name="1 2"/>
			<resource type="room" name="ETO"/>
		</event>
  </events>
</ttm>
<!-- End of file -->
<!-- End of file -->

=== Shmuma/tablix-operators/tablix2-0.3.5/ttf/tests/bug-consecutive-fixedtime-2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ttm PUBLIC "-//Tablix//DTD TTM 0.2.0//EN" "http://www.tablix.org/releases/dtd/tablix2r1.dtd">
<!--
BEGIN TTF BLOCK
(define periods 7)
(define (get-period tupleid) (modulo (get-time tupleid) periods))
(define (get-day tupleid) (quotient (get-time tupleid) periods))

(test-ttf
	(time 0 (get-time 1))
	(time 4 (get-time 3))
	(= (get-period 1) 0)
	(= (get-day 1) 0)
	(= (get-period 4) 1)
	(= (get-day 4) 1)
)
END TTF BLOCK
-->
<ttm version="0.2.0">
	<modules>
		<module name="sametime.so" weight="60" mandatory="yes"/> 
		<module name="timeplace.so" weight="60" mandatory="yes"/>
		<module name="sametimeas.so" weight="60" mandatory="yes"/>
		<module name="fixedtime.so" weight="60" mandatory="yes"/>
	</modules>

	<resources>
		<constant>
			<resourcetype type="teacher">
				<linear name="#" from="1" to="5"/>
			</resourcetype>
			<resourcetype type="class">
				<linear name="#" from="1" to="5"/>
			</resourcetype>
		</constant>
		<variable>
			<resourcetype type="room">
				<linear name="#" from="1" to="40"/>
			</resourcetype>
			<resourcetype type="time">
				<matrix width="5" height="7"/>
			</resourcetype>
		</variable>
	</resources>

	<events>
		<!-- 0 -->
		<event name="test1" repeats="1">
			<resource type="teacher" name="1"/>
			<resource type="class" name="1"/>
			<restriction type="same-time-as">test2</restriction>
		</event>
		<!-- 1 -->
		<event name="test2" repeats="1">
			<resource type="teacher" name="2"/>
			<resource type="class" name="2"/>
			<restriction type="fixed-day">0</restriction>
			<restriction type="fixed-period">0</restriction>
		</event>
		<!-- 2 -->
		<event name="test3" repeats="1">
			<resource type="teacher" name="3"/>
			<resource type="class" name="3"/>
		</event>
		<!-- 3 -->
		<event name="test4" repeats="1">
			<resource type="teacher" name="4"/>
			<resource type="class" name="4"/>
			<restriction type="same-time-as">test5</restriction>
		</event>
		<!-- 4 -->
		<event name="test5" repeats="1">
			<resource type="teacher" name="5"/>
			<resource type="class" name="5"/>
			<restriction type="fixed-day">1</restriction>
			<restriction type="fixed-period">1</restriction>
		</event>
	</events>
</ttm>
