=== Shmuma/tablix-operators/tablix2-0.3.5/examples/tablix2r1.dtd
<!-- ======================================================================

     Tablix Timetabling Model XML DTD, version 0.2.0R1
     File tablix2r1.dtd

     Copyright (C) 2002-2006 Tomaz Solc

     This program is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation; either version 2 of the License, or
     (at your option) any later version.

     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with this program; if not, write to the Free Software
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

     $Id: tablix2r1.dtd,v 1.1 2006-03-27 16:04:20 avian Exp $
     
     ====================================================================== 
     
     This is an XML document type definition (DTD) file for files describing
     timetabling problems according to the Tablix timetabling model version
     0.2.0.
     
     Please use the following DOCTYPE declaration to identify this file:
     
	<!DOCTYPE ttm PUBLIC "-//Tablix//DTD TTM 0.2.0//EN" 
			"http://www.tablix.org/releases/dtd/tablix2r1.dtd"> 
	
     ====================================================================== -->

<!ELEMENT ttm (info?,modules,resources,events)>
	<!ATTLIST ttm version CDATA #REQUIRED
	              fitness CDATA #IMPLIED>
        <!ELEMENT info (title?,address?,author?)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT address (#PCDATA)>
                <!ELEMENT author (#PCDATA)>
        <!ELEMENT modules (module+)>
                <!ELEMENT module (option*)>
		<!ATTLIST module name CDATA #REQUIRED
				 weight CDATA #REQUIRED
				 mandatory (yes|no) #REQUIRED>
			<!ELEMENT option (#PCDATA)>
			<!ATTLIST option name CDATA #REQUIRED>
        <!ELEMENT resources (constant?,variable?)>
                <!ELEMENT constant (resourcetype+)>
		<!ELEMENT variable (resourcetype+)>
			<!ELEMENT resourcetype ((resource|linear|matrix)+)>
                	<!ATTLIST resourcetype type CDATA #REQUIRED
			                       typeid CDATA #IMPLIED>
				<!ELEMENT resource (restriction*)>
				<!ATTLIST resource name CDATA #REQUIRED
				                   type CDATA #IMPLIED
						   resid CDATA #IMPLIED>
				<!ELEMENT linear (restriction*)>
				<!ATTLIST linear name CDATA #REQUIRED
				                 from CDATA #REQUIRED
						 to CDATA #REQUIRED
						 resid-from CDATA #IMPLIED
						 resid-to CDATA #IMPLIED>
				<!ELEMENT matrix (restriction*)>
				<!ATTLIST matrix width CDATA #REQUIRED
				                 height CDATA #REQUIRED
						 resid-from CDATA #IMPLIED
						 resid-to CDATA #IMPLIED>
        <!ELEMENT events (event+)>
		<!ELEMENT event (resource|restriction)*>
		<!ATTLIST event name CDATA #REQUIRED
		                repeats CDATA #REQUIRED
				tupleid CDATA #IMPLIED>

        <!ELEMENT restriction (#PCDATA)>
        <!ATTLIST restriction type CDATA #REQUIRED>

=== Shmuma/tablix-operators/tablix2-0.3.5/examples/multi-week.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ttm PUBLIC "-//Tablix//DTD TTM 0.2.0//EN" "http://www.tablix.org/releases/dtd/tablix2r1.dtd">

<!-- ======================================================================

     Example XML data file for Tablix 0.3.2                               
     Copyright (C) 2002-2006 Tomaz Solc                        

     File multi-week.xml

     $Id: multi-week.xml,v 1.4 2006-05-15 12:42:18 avian Exp $

     ======================================================================

     This file demonstrates the use of Tablix for multi-week scheduling.

     It describes a small 10 week course that includes mathematics, physics
     and engineering.

     Please see comments below for descriptions of various parts of the 
     file.

     ====================================================================== -->

<ttm version="0.2.0">
	<modules>
		<module name="sametime.so" weight="60" mandatory="yes"/> 
		<module name="timeplace.so" weight="60" mandatory="yes"/>
		<module name="recurrence.so" weight="60" mandatory="yes"/> 
		<module name="freemorning.so" weight="60" mandatory="yes">
			<option name="resourcetype">class</option>
			<option name="resourcetype">teacher</option>
		</module>
		<module name="walk.so" weight="60" mandatory="yes">
			<option name="resourcetype">class</option>
			<option name="resourcetype">teacher</option>
		</module>
		<!--		
		<module name="perday.so" weight="2" mandatory="no">
			<option name="resourcetype">class</option>
			<option name="resourcetype">teacher</option>
		</module> 
		-->
 		<module name="consecutive.so" weight="60" mandatory="yes"/>
		<module name="placecapability.so" weight="60" mandatory="yes"/>
	</modules>

	<resources>
		<constant>
			<resourcetype type="teacher">
				<!-- 
				
				This course is held by 3 professors
				
				-->
				<resource name="Anne"/>
				<resource name="Boris"/>
				<resource name="Greg"/>
			</resourcetype>
			<resourcetype type="class">
				<!-- 
				
				There are three groups of students.

				Each group has its own set of lectures. 
				Students from all groups also visit one 
				lecture in the big auditorium.

				-->

				<linear name="#" from="1" to="3"/>
				<resource name="All">
					<restriction type="conflicts-with">1</restriction>
					<restriction type="conflicts-with">2</restriction>
					<restriction type="conflicts-with">3</restriction>
				</resource>
			</resourcetype>
		</constant>
		<variable>
			<resourcetype type="room">
				<!-- 
				
				We can use three rooms in the building:

				The big auditorium, a small classroom and
				a laboratory.

				-->
				<resource name="Big classroom">
					<restriction type="capability">big</restriction>
					<restriction type="capability">classroom</restriction>
				</resource>
				<resource name="Small classroom">
					<restriction type="capability">classroom</restriction>
				</resource>
				<resource name="Lab">
					<restriction type="capability">lab</restriction>
				</resource>
			</resourcetype>
			<resourcetype type="time">
				<!--

				The course takes 10 weeks. Each week has 
				5 days (Monday - Friday).

				There are a maximum of 3 timeslots per day.

				(use weeksize=5 option with htmlcss2 export
				module)

				-->
				<matrix width="50" height="3"/>
			</resourcetype>
		</variable>
	</resources>

	<events>
		<!-- 

		Each group of students visits its own lecture of mathematics.

		The first group of students starts visiting this lecture on 
		the first week. It has 4 timeslots of mathematics (2 blocks of
		2 timeslots) per week. 20 timeslots of mathematics all together.

		The second group starts visiting this lecture on the 6th week.

		The third group start on the 4th week.

		-->
		<event name="Mathematics" repeats="20">
			<resource type="teacher" name="Boris"/>
			<resource type="class" name="1"/>
			<restriction type="recurrence">0 4</restriction>
			<restriction type="periods-per-block">2</restriction>
			<restriction type="capability">classroom</restriction>
		</event>
		<event name="Mathematics" repeats="20">
			<resource type="teacher" name="Boris"/>
			<resource type="class" name="2"/>
			<restriction type="recurrence">5 4</restriction>
			<restriction type="periods-per-block">2</restriction>
			<restriction type="capability">classroom</restriction>
		</event>
		<event name="Mathematics" repeats="20">
			<resource type="teacher" name="Boris"/>
			<resource type="class" name="3"/>
			<restriction type="recurrence">3 4</restriction>
			<restriction type="periods-per-block">2</restriction>
			<restriction type="capability">classroom</restriction>
		</event>

		<!-- 

		First and third group of students visits a lecture of 
		physics.

		The first group of students starts visiting this lecture on 
		the 7th week. It has 6 timeslots (2 blocks of 3 timeslots) 
		per week. 24 timeslots of mathematics all together.

		The second group starts visiting this lecture on the 1st week.

		-->
		<event name="Physics Lecture" repeats="24">
			<resource type="teacher" name="Anne"/>
			<resource type="class" name="1"/>
			<restriction type="recurrence">6 6</restriction>
			<restriction type="periods-per-block">3</restriction>
			<restriction type="capability">classroom</restriction>
		</event>
		<event name="Physics Lecture" repeats="24">
			<resource type="teacher" name="Anne"/>
			<resource type="class" name="3"/>
			<restriction type="recurrence">0 6</restriction>
			<restriction type="periods-per-block">3</restriction>
			<restriction type="capability">classroom</restriction>
		</event>

		<!-- 

		These two groups also have lab practice.

		-->

		<event name="Physics Lab" repeats="6">
			<resource type="teacher" name="Anne"/>
			<resource type="class" name="1"/>
			<restriction type="recurrence">7 2</restriction>
			<restriction type="periods-per-block">2</restriction>
			<restriction type="capability">lab</restriction>
		</event>
		<event name="Physics Lab" repeats="6">
			<resource type="teacher" name="Anne"/>
			<resource type="class" name="3"/>
			<restriction type="recurrence">1 2</restriction>
			<restriction type="periods-per-block">2</restriction>
			<restriction type="capability">lab</restriction>
		</event>

		<!--

		All three groups also visit a common lecture on engineering.

		This lecture must be scheduled in the big auditorium (the
		small classroom does not have enough seats).

		-->

		<event name="Mechanical Engineering" repeats="12">
			<resource type="teacher" name="Greg"/>
			<resource type="class" name="All"/>
			<restriction type="recurrence">4 3</restriction>
			<restriction type="periods-per-block">3</restriction>
			<restriction type="capability">big</restriction>
		</event>
	</events>
</ttm>

=== Shmuma/tablix-operators/room_avail.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ttm PUBLIC "-//Tablix//DTD TTM 0.2.0//EN" "http://www.tablix.org/releases/dtd/tablix2r1.dtd">

<ttm version="0.2.0">
  <info>
    <title>Room availabilty module test</title>
    <address>www.yandex.ru</address>
    <author>Max Lapan</author>
  </info>
  <modules>
    <module name="available" weight="200" mandatory="yes"/>
    <module name="timeplace" weight="500" mandatory="yes"/>
    <module name="sametimelight" weight="500" mandatory="yes"/>
    <module name="room_available" weight="500" mandatory="yes"/>
    <module name="nights" weight="500" mandatory="yes">
      <option name="max-nights-per-week">2</option>
      <option name="max-nights-weight">100</option>
    </module>
    <module name="time_descriptions" weight="0" mandatory="no">
      <option name="output">time_descr.txt</option>
    </module>
    <module name="shift" weight="500" mandatory="yes">
      <option name="hours">8</option>
      <option name="distance">8</option>
    </module>
  </modules>

  <resources>
    <constant>
      <resourcetype type="operator">
        <resource name="airdog">
          <restriction type="allow-near-shifts">1</restriction>
        </resource>
        <resource name="alex27j"></resource>
        <resource name="astronom"></resource>
        <resource name="shpin"></resource>
        <resource name="teran">
        </resource>
        <resource name="shmuma"></resource>
      </resourcetype>
    </constant>

    <variable>
      <resourcetype type="time">
        <matrix width="7" height="3"/>
      </resourcetype>

      <resourcetype type="room">
        <resource name="Vavilova">
          <restriction type="room-not-available-time">0</restriction>
          <restriction type="room-not-available-day">5</restriction>
          <restriction type="room-not-available-day">6</restriction>
          <restriction type="time-descriptions">23:00,07:00,15:00</restriction>
        </resource>
        <resource name="ETO">
          <restriction type="room-not-available-cell">1 2</restriction>
          <restriction type="time-descriptions">23:00,07:00,15:00</restriction>
        </resource>
      </resourcetype>
    </variable>
  </resources>

  <events>
    <event name="Work" repeats="5">
        <resource type="operator" name="airdog"/>
    </event>
    <event name="Work" repeats="5">
        <resource type="operator" name="alex27j"/>
    </event>
    <event name="Work" repeats="5">
        <resource type="operator" name="astronom"/>
    </event>
    <event name="Work" repeats="5">
        <resource type="operator" name="shpin"/>
    </event>
    <event name="Work" repeats="5">
        <resource type="operator" name="teran"/>
    </event>
  </events>
</ttm>

=== Shmuma/tablix-operators/tablix2-0.3.5/ttf/tests/bug-sametimeas-1.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE ttm PUBLIC "-//Tablix//DTD TTM 0.2.0//EN" "http://www.tablix.org/releases/dtd/tablix2r1.dtd">

<!-- 

No script required. Bug causes the following error message on startup

Constant resource 'teacher1' (type 'teacher') has 0.0 blocks of 'test1' events 
defined and maximum 2147483647 blocks per day, however only 4 days are defined

-->

<!-- 
BEGIN TTF BLOCK
(test-ttf
	#t
)
END TTF BLOCK
-->

<ttm version="0.2.0">
        <modules>
                <module name="sametime.so" weight="60" mandatory="yes"/> 
                <module name="timeplace.so" weight="60" mandatory="yes"/> 
                <module name="sameday.so" weight="60" mandatory="yes"> 
			<option name="resourcetype">teacher</option>
		</module>
         </modules>

	<resources>
		<constant>
			<resourcetype type="teacher">
				<resource name="teacher1">
					<restriction type="ignore-sameday"/>
				</resource>
				<resource name="teacher2"/>
			</resourcetype>
			<resourcetype type="class">
				<resource name="class1"/>
			</resourcetype>
		</constant>
		<variable>
			<resourcetype type="time">
				<matrix width="4" height="7"/>
			</resourcetype>
			<resourcetype type="room">
				<resource name="room1"/>
			</resourcetype>
		</variable>
	</resources>

	<events>
		<event name="test1" repeats="1">
			<resource type="teacher" name="teacher1"/>
			<resource type="class" name="class1"/>
		</event>
	</events>
</ttm>

=== Shmuma/tablix-operators/tablix2-0.3.5/ttf/tests/available-1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ttm PUBLIC "-//Tablix//DTD TTM 0.2.0//EN" "http://www.tablix.org/releases/dtd/tablix2r1.dtd">
<!--
BEGIN TTF BLOCK
(define periods 10)
(define days 10)

(define bad-time-1 (+ 4 (* 4 periods)))
(define bad-time-2 (+ 5 (* 1 periods)))

(define (tuple-loop i j ok)
	(if (< i j)
		(tuple-loop (+ i 1) j 
			(and 
				ok 
				(not (time i bad-time-1))
				(not (time i bad-time-2))
			)
		)
		ok
	)
	
)
(test-ttf
	(tuple-loop 0 98 #t)
)
END TTF BLOCK
-->
<ttm version="0.2.0">
	<modules>
		<module name="sametime.so" weight="60" mandatory="yes"/> 
		<module name="timeplace.so" weight="60" mandatory="yes"/>
		<module name="available.so" weight="60" mandatory="yes"/>
	</modules>

	<resources>
		<constant>
			<resourcetype type="teacher">
				<resource name="a">
					<restriction type="not-available">4 4</restriction>
				</resource>
			</resourcetype>
			<resourcetype type="class">
				<resource name="1">
					<restriction type="not-available">1 5</restriction>
				</resource>
			</resourcetype>
		</constant>
		<variable>
			<resourcetype type="room">
				<resource name="1">
				</resource>
			</resourcetype>
			<resourcetype type="time">
				<matrix width="10" height="10"/>
			</resourcetype>
		</variable>
	</resources>

	<events>
		<event name="test" repeats="98">
			<resource type="teacher" name="a"/>
			<resource type="class" name="1"/>
		</event>
	</events>
</ttm>

=== Shmuma/tablix-operators/test.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ttm PUBLIC "-//Tablix//DTD TTM 0.2.0//EN" "http://www.tablix.org/releases/dtd/tablix2r1.dtd">

<ttm version="0.2.0">
  <info>
    <title>Yandex DC</title>
    <address>www.yandex.ru</address>
    <author>Max Lapan</author>
  </info>
  <modules>
    <module name="available" weight="200" mandatory="yes"/>
    <module name="timeplace" weight="500" mandatory="yes"/>
    <module name="sametimelight" weight="200" mandatory="yes"/>
    <module name="maxperday" weight="60" mandatory="yes">
      <option name="resourcetype">teacher</option>
      <option name="maxperday">1</option>
    </module>
    <module name="walk" weight="500" mandatory="yes">
      <option name="resourcetype">teacher</option>
    </module>
  </modules>

  <resources>
    <constant>
      <resourcetype type="teacher">
        <resource name="shmuma">
          <restriction type="not-available">0 0</restriction>
        </resource>
        <resource name="efim">
          <restriction type="not-available">0 0</restriction>
        </resource>
        <resource name="legion">
          <restriction type="not-available">0 0</restriction>
        </resource>
        <resource name="nab">
          <restriction type="not-available">0 0</restriction>
        </resource>
        <resource name="khext">
          <restriction type="not-available">0 0</restriction>
        </resource>
        <resource name="andozer">
          <restriction type="not-available">0 0</restriction>
        </resource>
        <resource name="guba"/>
        <resource name="ezhichek"/>
        <resource name="scheg0l">
          <restriction type="not-available">0 0</restriction>
        </resource>
      </resourcetype>
    </constant>

    <variable>
      <resourcetype type="time">
        <matrix width="7" height="3"/>
      </resourcetype>
      <resourcetype type="room">
        <resource name="dc1"/>
        <resource name="dc2"/>
      </resourcetype>
    </variable>
  </resources>

  <events>
    <event name="Work" repeats="5">
      <resource type="teacher" name="shmuma"/>
    </event>
    <event name="Work" repeats="5">
      <resource type="teacher" name="efim"/>
    </event>
    <event name="Work" repeats="5">
      <resource type="teacher" name="legion"/>
    </event>
    <event name="Work" repeats="5">
      <resource type="teacher" name="nab"/>
    </event>
    <event name="Work" repeats="5">
      <resource type="teacher" name="khext"/>
    </event>
    <event name="Work" repeats="5">
      <resource type="teacher" name="andozer"/>
    </event>
    <event name="Work" repeats="5">
      <resource type="teacher" name="guba"/>
    </event>
    <event name="Work" repeats="5">
      <resource type="teacher" name="ezhichek"/>
    </event>
    <event name="Work" repeats="2">
      <resource type="teacher" name="scheg0l"/>
    </event>
  </events>
</ttm>

=== Shmuma/tablix-operators/preference.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ttm PUBLIC "-//Tablix//DTD TTM 0.2.0//EN" "http://www.tablix.org/releases/dtd/tablix2r1.dtd">

<ttm version="0.2.0">
  <info>
    <title>User's preferences module test</title>
    <address>www.yandex.ru</address>
    <author>Max Lapan</author>
  </info>
  <modules>
    <module name="available" weight="200" mandatory="yes"/>
    <module name="timeplace" weight="500" mandatory="yes"/>
    <module name="sametimelight" weight="500" mandatory="yes"/>
    <module name="room_available" weight="500" mandatory="yes">
      <option name="debug">0</option>
    </module>
    <module name="preference" weight="50" mandatory="no"/>
    <module name="time_descriptions" weight="0" mandatory="no">
      <option name="output">time_descr.txt</option>
    </module>
  </modules>

  <resources>
    <constant>
      <resourcetype type="operator">
        <resource name="airdog"></resource>
        <resource name="alex27j"></resource>
        <resource name="astronom"></resource>
        <resource name="shpin">
          <restriction type="pref-room">!2 ETO</restriction>
          <restriction type="pref-room">1 Golem</restriction>
        </resource>
        <resource name="teran">
          <restriction type="pref-room">2 ETO</restriction>
          <restriction type="pref-room">2 Vavilova</restriction>
          <restriction type="pref-time-day">!2 0</restriction>
          <restriction type="pref-time-time">!2 0</restriction>
          <restriction type="pref-time-cell">!2 1 2</restriction>
        </resource>
        <resource name="shmuma">
          <restriction type="pref-room">1 Vavilova</restriction>
          <restriction type="pref-room">!1 ETO</restriction>
        </resource>
      </resourcetype>
    </constant>

    <variable>
      <resourcetype type="time">
        <matrix width="7" height="3"/>
      </resourcetype>

      <resourcetype type="room">
        <resource name="Vavilova">
          <restriction type="time-descriptions">23:00,07:00,15:00</restriction>
          <restriction type="room-not-available-time">0</restriction>
          <restriction type="room-not-available-day">5</restriction>
          <restriction type="room-not-available-day">6</restriction>
        </resource>
        <resource name="ETO">
          <restriction type="time-descriptions">23:00,07:00,15:00</restriction>
          <restriction type="room-must-be-filled">0</restriction>
          <restriction type="room-must-be-filled">1</restriction>
          <restriction type="room-must-be-filled">2</restriction>
          <restriction type="room-not-available-cell">1 2</restriction>
          <restriction type="room-not-available-day">5</restriction>
        </resource>
        <resource name="Golem">
          <restriction type="room-must-be-filled">0</restriction>
          <restriction type="room-must-be-filled">1</restriction>
          <restriction type="time-descriptions">23:00,07:00,15:00</restriction>
        </resource>
      </resourcetype>
    </variable>
  </resources>

  <events>
    <event name="Work" repeats="4">
        <resource type="operator" name="airdog"/>
    </event>
    <event name="Work" repeats="4">
        <resource type="operator" name="alex27j"/>
    </event>
    <event name="Work" repeats="4">
        <resource type="operator" name="astronom"/>
    </event>
    <event name="Work" repeats="4">
        <resource type="operator" name="shpin"/>
    </event>
    <event name="Work" repeats="10">
        <resource type="operator" name="teran"/>
    </event>
    <event name="Work" repeats="10">
        <resource type="operator" name="shmuma"/>
    </event>
  </events>
</ttm>
