=== Shmuma/tablix-operators/tablix2-0.3.5/doc/modulesref2r0.dtd
<!-- ======================================================================

     Tablix fitness modules reference documentation DTD, version 0.2.1R0
     File modulesref2r0.dtd

     Copyright (C) 2002-2006 Tomaz Solc                                      

     This program is free software; you can redistribute it and/or modify    
     it under the terms of the GNU General Public License as published by    
     the Free Software Foundation; either version 2 of the License, or       
     (at your option) any later version.                                     

     This program is distributed in the hope that it will be useful,         
     but WITHOUT ANY WARRANTY; without even the implied warranty of          
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           
     GNU General Public License for more details.                            

     You should have received a copy of the GNU General Public License       
     along with this program; if not, write to the Free Software             
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA 

     $Id: modulesref2r0.dtd,v 1.3 2006-05-25 16:54:47 avian Exp $ 
     
     ====================================================================== 
     
     This is an XML document type definition (DTD) file for files containing
     reference documentation for fitness modules for Tablix.
     
     Please use the following DOCTYPE declaration to identify this file:
     
	<!DOCTYPE module-documentation PUBLIC 
		"-//Tablix//DTD Module Reference 0.2.1//EN" 
		"http://www.tablix.org/releases/dtd/modulesref2r0.dtd"> 
	
     ====================================================================== -->

<!ENTITY % block "p|pre">

<!ENTITY % fontstyle "tt|i|b">

<!ENTITY % inline "#PCDATA|%fontstyle;">

<!ELEMENT p (%inline;)*>
<!ELEMENT pre (%inline;)*>

<!ELEMENT required-resourcetypes (resourcetype*|all-resourcetypes)>
<!ELEMENT all-resourcetypes EMPTY>
<!ELEMENT resourcetype (#PCDATA)>

<!ELEMENT description (%block;)*>

<!ELEMENT name (#PCDATA)>

<!ELEMENT module-documentation (module*)>
        <!ELEMENT module (basic-info,module-groups,description,required-resourcetypes,defined-resource-restrictions,defined-tuple-restrictions,defined-options)>
		<!ELEMENT basic-info (filename,author,authoremail?,credits?)>
			<!ELEMENT filename (#PCDATA)>
			<!ELEMENT author (#PCDATA)>
			<!ELEMENT authoremail (#PCDATA)>
			<!ELEMENT credits ((%block;)*)>
                <!ELEMENT module-groups (group+)>
			<!ELEMENT group (#PCDATA)>
		<!ELEMENT defined-resource-restrictions (resource-restriction*)>
			<!ELEMENT resource-restriction (name,required-resourcetypes,description)>
		<!ELEMENT defined-tuple-restrictions (tuple-restriction*)>
			<!ELEMENT tuple-restriction (name,description)>
		<!ELEMENT defined-options (module-option*)>
			<!ELEMENT module-option (name,description)>

=== Shmuma/tablix-operators/tablix2-0.3.5/doc/modulesref.xml
<!DOCTYPE module-documentation PUBLIC "-//Tablix//DTD Module Reference 0.2.1//EN" "http://www.tablix.org/releases/dtd/modulesref2r0.dtd">
<module-documentation>
	<module>
		<basic-info>
			<filename>available.so</filename>
			<author>Tomaz Solc</author>
			<authoremail>tomaz.solc@tablix.org</authoremail>
		</basic-info>
		<module-groups>
			<group>School scheduling</group>
			<group>General</group>
			<group>Multiweek scheduling</group>
		</module-groups>
		<description>
<p>Specifies that a particular constant resource is not available 
at certain timeslots.</p>
<p>There is no fitness function, so the "weight" and "mandatory" module 
options are ignored (restrictions set by this module are always mandatory).</p>
		</description>
		<required-resourcetypes>
			<resourcetype>time</resourcetype>
		</required-resourcetypes>
		<defined-resource-restrictions>
			<resource-restriction>
				<name>not-available</name>
				<required-resourcetypes>
					<all-resourcetypes/>
				</required-resourcetypes>
				<description>
<pre>&lt;restriction type="not-available"&gt;day period&lt;/restriction&gt;</pre>
<p>This tuple restriction specifies that the current resource is not available
at time slot at the specified day and period.</p>
<p>For example:</p>
<pre>&lt;resourcetype type="teacher"&gt;
	&lt;resource name="A"&gt;
		&lt;restriction type="not-available"&gt;1 1&lt;/restriction&gt;
	&lt;/resource&gt;
&lt;/resource&gt;</pre>
<p>This means that no event for teacher A will be scheduled on the second 
period of the second day (day and period numbers start at 0).</p>
				</description>
			</resource-restriction>
		</defined-resource-restrictions>
		<defined-tuple-restrictions>
		</defined-tuple-restrictions>
		<defined-options>
		</defined-options>
	</module>
	<module>
		<basic-info>
			<filename>consecutive.so</filename>
			<author>Tomaz Solc</author>
			<authoremail>tomaz.solc@tablix.org</authoremail>
			<credits>
<p>
Original idea for this module by Nick Robinson (npr@bottlehall.co.uk).
Module was later rewritten to serve as an example for the new updater 
function feature in 0.3.1 by Tomaz Solc.</p>
			</credits>
		</basic-info>
		<module-groups>
			<group>School scheduling</group>
			<group>Multiweek scheduling</group>
		</module-groups>
		<description>
<p>Adds support for events that must be scheduled adjacent to one
another. This module uses updater functions, so the weight and mandatory
values are ignored.</p>
		</description>
		<required-resourcetypes>
			<resourcetype>time</resourcetype>
		</required-resourcetypes>
		<defined-resource-restrictions>
		</defined-resource-restrictions>
		<defined-tuple-restrictions>
			<tuple-restriction>
				<name>consecutive</name>
				<description>
<p>This restriction specifies that the repeats of the current event need to 
be scheduled consecutively.</p>
<p>Please note that this module distinguishes events by the 
assignments of constant resources and event names. The way events are 
defined in the XML file has no effect. The following two examples will 
therefore both result in one block of four consecutive "Lecture" events.</p>
<p>Example 1:</p>
<pre>&lt;event name ="Lecture" repeats="2"&gt;
	&lt;resource type="teacher"  name="A"/&gt;
	&lt;resource type="class"  name="B"/&gt;
	&lt;restriction type="consecutive"/&gt;
&lt;/event&gt;
&lt;event name ="Lecture" repeats="2"&gt;
	&lt;resource type="teacher"  name="A"/&gt;
	&lt;resource type="class"  name="B"/&gt;
	&lt;restriction type="consecutive"/&gt;
&lt;/event&gt;</pre>
<p>Example 2:</p>
<pre>&lt;event name ="Lecture" repeats="4"&gt;
	&lt;resource type="teacher"  name="A"/&gt;
	&lt;resource type="class"  name="B"/&gt;
	&lt;restriction type="consecutive"/&gt;
&lt;/event&gt;</pre>
<p>If you would like to have two blocks of two consecutive "Lecture" events, 
you must either change the names of two events like in the following example 
or use the periods-per-block restriction.</p>
<pre>&lt;event name ="Lecture 1" repeats="2"&gt;
	&lt;resource type="teacher"  name="A"/&gt;
	&lt;resource type="class"  name="B"/&gt;
	&lt;restriction type="consecutive"/&gt;
&lt;/event&gt;
&lt;event name ="Lecture 2" repeats="2"&gt;
	&lt;resource type="teacher"  name="A"/&gt;
	&lt;resource type="class"  name="B"/&gt;
	&lt;restriction type="consecutive"/&gt;
&lt;/event&gt;</pre>
				</description>
			</tuple-restriction>
			<tuple-restriction>
				<name>periods-per-block</name>
				<description>
<p>This restriction specifies that the repeats of the current event need to 
be scheduled blocks of N consecutive events. If the number of repeats is
not divisible by N, then one block will have less than N events.</p>
<p>Events in the following example will be scheduled in two blocks of three
consecutive events, two blocks of two consecutive events and one single
event.</p>
<pre>&lt;event name ="Lecture" repeats="6"&gt;
	&lt;resource type="teacher" name="A"/&gt;
	&lt;resource type="class" name="B"/&gt;
	&lt;restriction type="periods-per-block"&gt;3&lt;/restriction&gt;
&lt;/event&gt;
&lt;event name ="Lecture" repeats="5"&gt;
	&lt;resource type="teacher" name="A"/&gt;
	&lt;resource type="class" name="B"/&gt;
	&lt;restriction type="periods-per-block"&gt;2&lt;/restriction&gt;
&lt;/event&gt;</pre>
				</description>
			</tuple-restriction>
		</defined-tuple-restrictions>
		<defined-options>
		</defined-options>
	</module>
	<module>
		<basic-info>
			<filename>events_sameday.so</filename>
			<author>Antonio Duran</author>
			<authoremail>antonio.duran.terres@gmail.com</authoremail>
			<credits>
<p>
Modified by Tomaz Solc</p>
			</credits>
		</basic-info>
		<module-groups>
			<group>School scheduling</group>
			<group>General</group>
		</module-groups>
		<description>
<p>
Adds a weight if two specified events are scheduled on the same day.</p>
		</description>
		<required-resourcetypes>
			<resourcetype>time</resourcetype>
		</required-resourcetypes>
		<defined-resource-restrictions>
		</defined-resource-restrictions>
		<defined-tuple-restrictions>
			<tuple-restriction>
				<name>not-same-day-as</name>
				<description>
<p>Set this restriction to prevent the current event from being scheduled in 
the same day as the one specified in the restriction.</p>
<p>Example:</p>
<pre>&lt;event name="A" repeats="3"&gt;
	...
	&lt;restriction type="not-same-day-as"&gt;B&lt;/restriction&gt;
&lt;/event&gt;
&lt;event name="B" repeats="4"&gt;
	...
&lt;/event&gt;</pre>
<p>In this example no "A" event will be scheduled on the same day as a "B"
event</p>
				</description>
			</tuple-restriction>
		</defined-tuple-restrictions>
		<defined-options>
		</defined-options>
	</module>
	<module>
		<basic-info>
			<filename>firstlastequal.so</filename>
			<author>Tomaz Solc</author>
			<authoremail>tomaz.solc@tablix.org</authoremail>
		</basic-info>
		<module-groups>
			<group>School scheduling</group>
		</module-groups>
		<description>
<p>This module counts the number of occupied first and last time slots in
teacher's (or any other constant resource type) timetables. The number of 
weights added is equal to the difference between the number of occupied 
first time slots and the number of occupied last time slots.</p>
<p>For example if a teacher has two events scheduled on the first time slot in 
a day then it must also have two events scheduled on the last time slot. 
(E.g. A teacher teaches first period for Monday and Tuesday, and the last 
period for Wednesday, Tuesday, Friday. So that he/she can go home earlier 
on Monday/Tuesday and come in later on Wednesday, Tuesday, Friday.)</p>
<p>The following example will make this module check teacher's timetable:</p>
<pre>&lt;module name="firstlastequal" weight="60" mandatory="yes"&gt;
	&lt;option name="resourcetype"&gt;teacher&lt;/option&gt;
&lt;/module&gt;</pre>
		</description>
		<required-resourcetypes>
			<resourcetype>time</resourcetype>
		</required-resourcetypes>
		<defined-resource-restrictions>
		</defined-resource-restrictions>
		<defined-tuple-restrictions>
		</defined-tuple-restrictions>
		<defined-options>
			<module-option>
				<name>resourcetype</name>
				<description>
<p>Use this option to specify a constant resource type for which this module
will be in effect.</p>
<p>You can use multiple resourcetype options for one module.</p>
				</description>
			</module-option>
		</defined-options>
	</module>
	<module>
		<basic-info>
			<filename>firstorlast.so</filename>
			<author>Tomaz Solc</author>
			<authoremail>tomaz.solc@tablix.org</authoremail>
		</basic-info>
		<module-groups>
			<group>School scheduling</group>
		</module-groups>
		<description>
<p>This module prevents constant resources of one type (for example
teachers) to have events scheduled on the first and the last time slots on 
the same day.</p>
<p>For example if a teacher has an event scheduled on the first time slot in 
a day then it must have the last time slot in that day free. On the other 
hand if a teacher has an event scheduled on the last time slot it must have 
the first time slot free.</p>
<p>The number of weights added by this module is equal to the number of days
in the timetable that do not conform to this constraint.</p>
<p>The following example will make this module check teacher's timetable:</p>
<pre>&lt;module name="firstorlast" weight="60" mandatory="yes"&gt;
	&lt;option name="resourcetype"&gt;teacher&lt;/option&gt;
&lt;/module&gt;</pre>
		</description>
		<required-resourcetypes>
			<resourcetype>time</resourcetype>
		</required-resourcetypes>
		<defined-resource-restrictions>
		</defined-resource-restrictions>
		<defined-tuple-restrictions>
		</defined-tuple-restrictions>
		<defined-options>
			<module-option>
				<name>resourcetype</name>
				<description>
<p>Use this option to specify a constant resource type for which this module
will be in effect.</p>
<p>You can use multiple resourcetype options for one module.</p>
				</description>
			</module-option>
		</defined-options>
	</module>
	<module>
		<basic-info>
			<filename>fixed.so</filename>
